name: CI Pipeline 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    name: Format, Lint and Test 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo 
        uses: actions/checkout@v3 

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install
          git lfs pull

      - name: Set up Python
        uses: actions/setup-python@v4 
        with:
          python-version: "3.10"

      - name: Install dependencies 
        run: | 
          pip install -r requirements.txt 
          pip install pytest black flake8 dvc[s3]

      # # ---- DVC STEPS ----
      # - name: Pull dataset from DVC remote
      #   run: |
      #     dvc pull
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: us-east-1

      # - name: Verify dataset is available
      #   run: ls -lh data/

      # ---- FORMAT + LINT ----
      - name: Reformat code with Black
        run: black .  # reformats all Python files from repo root

      - name: Check formatting with Black
        run: black --check .

      # - name: Lint with Flake8
      #   run: flake8 .
      
      # ---- TEST ----
      - name: Run unit tests
        run: pytest tests/

  airflow-dag-check:
    name: Run ML Pipelines
    runs-on: ubuntu-latest 

    steps:
      - name: checkout code 
        uses: actions/checkout@v3 

      - name: set up python 
        uses: actions/setup-python@v4 
        with:
          python-version: '3.10'

      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip 
          pip install apache-airflow==2.8.1 

      - name: Check DAG file syntax 
        run: | 
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python airflow_orchestrator/dags/ml_pipeline_dag.py


